### ISSUE TITLE
How to use stealth?

### ISSUE THREAD

**Issue by HelloAllenZHU** [go-rod/stealth#18]
Is here any complete example code?

**Comment by ysmood** [comment]
https://github.com/go-rod/stealth/blob/master/examples_test.go

**Comment by HelloAllenZHU** [comment]
@ysmood 
Thanks! I just want to open a website [https://coinlist.co](https://coinlist.co), which is protected by Cloudflare, but it doesn't work for me.

**Comment by ysmood** [comment]
Instead, what did you see?

**Comment by HelloAllenZHU** [comment]
> Instead, what did you see?

Chrome blocks at the Cloudflare checking page.

**Comment by ysmood** [comment]
It's the website itself is buggy, there's no problem with Rod or stealth. You don't need to use stealth:

```go
package main

import (
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/utils"
)

func main() {
	browser := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co")
	utils.Pause()
}
```

**Comment by HelloAllenZHU** [comment]
> It's the website itself is buggy, there's no problem with Rod or stealth (when using the default device the site will force you to reload again and again). You don't need to use stealth:
> 
> ```go
> package main
> 
> import (
> 	"github.com/go-rod/rod"
> 	"github.com/go-rod/rod/lib/utils"
> )
> 
> func main() {
> 	browser := rod.New().MustConnect().NoDefaultDevice().MustPage("https://coinlist.co")
> 	utils.Pause()
> }
> ```

Thanks for your help!
