### ISSUE TITLE
headless 问题

### ISSUE THREAD

**Issue by Nan3r** [go-rod/stealth#30]
使用stealth库，headless设置为true，就无法获取网页信息，但是设置为false，页面返回是403，这是啥原因。

**Comment by ysmood** [comment]
提供的信息太少

**Comment by Nan3r** [comment]
目标是cloudflare的网站，使用如下代码，headless设置为true，就无法获取网页信息，但是设置为false，可以看到打开了页面，并且代码也可以获得源代码。

cpath, _ := launcher.LookPath()
	u := launcher.New().
		Set(flags.ProxyServer, proxy).
		Headless(true).
		Set("no-first-run").
		Set("--no-sandbox").
		Set("--disable-setuid-sandbox").
		Set("--disable-dev-shm-usage").
		Set("--disable-web-security").
		Set("--disable-backgrounding-occluded-windows").
		Set("disable-default-apps").
		Delete("--enable-automation").
		Bin(cpath).
		MustLaunch()
	browser := rod.New().Timeout(time.Minute).ControlURL(u).NoDefaultDevice().MustConnect().MustIgnoreCertErrors(true)
	defer browser.MustClose()
	page := stealth.MustPage(browser)
	page.MustWindowMaximize()

**Comment by ysmood** [comment]
我没有这个问题
