### ISSUE TITLE
detection upgrade

### ISSUE THREAD

**Issue by dataflowjs** [go-rod/stealth#31]
current version has old version of navigator.plugins and navigator.mimeTypes, that is the problem, i think...
current stealth version have:
![2](https://github.com/go-rod/stealth/assets/11431176/2289dfc8-f5e8-48ba-99e7-04f43caf447e)
but new version chromium browser have default values in different object structure:
![1](https://github.com/go-rod/stealth/assets/11431176/43d91e28-cfa9-4dd0-9554-d6a756958b66)
i was test it in different detect sites (https://bot.sannysoft.com/ and other) and i think, just need to update navigator.plugins object to new version and navigator.mimeTypes in this package and after it will work fine becouse everything else is still fine

**Comment by ysmood** [comment]
stealth depends on https://www.npmjs.com/package/extract-stealth-evasions

It's already using the latest version of it.

**Comment by dataflowjs** [comment]
plugins length of stealth version is 3, but default version of new chromium browser is 5, and plugins name have difference.

**Comment by dataflowjs** [comment]
nevermine, the problem with cloudflare solved in headless mode.
